// Generated CSV contract importer for 河南医保目录 Neo4j V2.
// Execute only after validation_report.json reports passed=true.
CREATE CONSTRAINT import_batch_id IF NOT EXISTS FOR (n:ImportBatch) REQUIRE n.batch_id IS UNIQUE;
CREATE CONSTRAINT source_file_id IF NOT EXISTS FOR (n:SourceFile) REQUIRE n.source_id IS UNIQUE;
CREATE CONSTRAINT catalog_record_id IF NOT EXISTS FOR (n:CatalogRecord) REQUIRE n.record_id IS UNIQUE;
CREATE CONSTRAINT mapping_concept_namespace_code IF NOT EXISTS FOR (n:MappingConcept) REQUIRE (n.namespace, n.code) IS UNIQUE;
CREATE CONSTRAINT observed_label_key IF NOT EXISTS FOR (n:ObservedLabel) REQUIRE n.observed_label_id IS UNIQUE;
CREATE CONSTRAINT service_category_id IF NOT EXISTS FOR (n:ServiceCategory) REQUIRE n.service_category_id IS UNIQUE;
CREATE CONSTRAINT service_item_id IF NOT EXISTS FOR (n:ServiceItem) REQUIRE n.service_item_id IS UNIQUE;
CREATE CONSTRAINT diagnosis_item_id IF NOT EXISTS FOR (n:DiagnosisItem) REQUIRE n.diagnosis_item_id IS UNIQUE;
CREATE CONSTRAINT consumable_base_code IF NOT EXISTS FOR (n:ConsumableBase) REQUIRE n.base_code IS UNIQUE;
CREATE CONSTRAINT consumable_product_id IF NOT EXISTS FOR (n:ConsumableProduct) REQUIRE n.product_id IS UNIQUE;
CREATE CONSTRAINT consumable_sku_code IF NOT EXISTS FOR (n:ConsumableSku) REQUIRE n.sku_code IS UNIQUE;
CREATE CONSTRAINT basic_material_id IF NOT EXISTS FOR (n:BasicMaterial) REQUIRE n.basic_material_id IS UNIQUE;
CREATE CONSTRAINT drug_generic_id IF NOT EXISTS FOR (n:DrugGeneric) REQUIRE n.drug_generic_id IS UNIQUE;
CREATE CONSTRAINT drug_product_code IF NOT EXISTS FOR (n:DrugProduct) REQUIRE n.drug_code IS UNIQUE;
CREATE CONSTRAINT organization_id IF NOT EXISTS FOR (n:Organization) REQUIRE n.organization_id IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///import_batches.csv' AS row
CALL { WITH row MERGE (b:ImportBatch {batch_id: row.batch_id}) ON CREATE SET b.input_manifest_sha256=row.input_manifest_sha256,b.pipeline_version=row.pipeline_version,b.run_mode=row.run_mode,b.started_at=datetime(row.started_at),b.created_at=datetime() } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///source_files.csv' AS row
CALL { WITH row MATCH (b:ImportBatch {batch_id:row.batch_id}) MERGE (f:SourceFile {source_id:row.source_id}) ON CREATE SET f.file_name=row.file_name,f.sheet_name=row.sheet_name,f.file_sha256=row.file_sha256,f.created_at=datetime() MERGE (b)-[:CONTAINS_SOURCE]->(f) } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///catalog_records.csv' AS row
CALL { WITH row MATCH (f:SourceFile {source_id:row.source_id}) MERGE (r:CatalogRecord {record_id:row.record_id}) ON CREATE SET r.source_id=row.source_id,r.source_row=toInteger(row.source_row),r.raw_row_hash=row.raw_row_hash,r.raw_payload_base64=row.raw_payload_base64,r.raw_payload_encoding=row.raw_payload_encoding,r.record_kind=row.record_kind,r.created_at=datetime() MERGE (f)-[:CONTAINS_RECORD]->(r) } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///consumable_categories.csv' AS row
CALL { WITH row OPTIONAL MATCH (p:ConsumableCategory {category_path_id:row.parent_path_id}) MERGE (c:ConsumableCategory {category_path_id:row.category_path_id}) ON CREATE SET c.created_at=datetime() SET c.level=toInteger(row.level),c.code=row.code,c.name=row.name,c.path_kind=row.path_kind FOREACH (_ IN CASE WHEN p IS NULL THEN [] ELSE [1] END | MERGE (p)-[:PARENT_OF]->(c)) } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///mapping_concepts.csv' AS row
CALL { WITH row MERGE (c:MappingConcept {namespace:row.namespace,code:row.code}) ON CREATE SET c.first_seen_batch=row.first_seen_batch,c.created_at=datetime() SET c.classification_status=row.classification_status,c.classification_rule=row.classification_rule,c.review_status=row.review_status } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///service_categories.csv' AS row
CALL { WITH row MERGE (c:ServiceCategory {service_category_id:row.service_category_id}) ON CREATE SET c.namespace=row.namespace,c.code=row.code,c.created_at=datetime() SET c.name=row.name } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///service_items.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MERGE (s:ServiceItem {service_item_id:row.service_item_id}) ON CREATE SET s.province_code=row.province_code,s.created_at=datetime() SET s.name=row.name MERGE (v:CatalogRecordVersion {version_id:row.version_id}) ON CREATE SET v.domain='SERVICE',v.record_hash=row.record_hash,v.valid_from=CASE trim(row.valid_from) WHEN '' THEN null ELSE date(row.valid_from) END,v.valid_to=CASE trim(row.valid_to) WHEN '' THEN null ELSE date(row.valid_to) END,v.raw_valid_from=row.raw_valid_from,v.raw_valid_to=row.raw_valid_to,v.created_at=datetime() MERGE (record)-[:EVIDENCE_FOR]->(s) MERGE (record)-[:CAPTURED_AS_VERSION]->(v) MERGE (v)-[:VERSION_OF]->(s) } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///diagnosis_items.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MERGE (d:DiagnosisItem {diagnosis_item_id:row.diagnosis_item_id}) ON CREATE SET d.namespace=row.namespace,d.code=row.code,d.created_at=datetime() SET d.name=row.name,d.valid_from=CASE trim(row.valid_from) WHEN '' THEN null ELSE date(row.valid_from) END,d.valid_to=CASE trim(row.valid_to) WHEN '' THEN null ELSE date(row.valid_to) END MERGE (record)-[:EVIDENCE_FOR]->(d) } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///consumable_bases.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MATCH (c:ConsumableCategory {category_path_id:row.feature_path_id}) MERGE (b:ConsumableBase {base_code:row.base_code}) ON CREATE SET b.created_at=datetime() SET b.code_rule_valid=toBoolean(row.code_rule_valid) MERGE (b)-[:CLASSIFIED_AS]->(c) MERGE (record)-[:EVIDENCE_FOR]->(b) } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///consumable_products.csv' AS row
CALL { WITH row MATCH (b:ConsumableBase {base_code:row.base_code}) MERGE (p:ConsumableProduct {product_id:row.product_id}) ON CREATE SET p.base_code=row.base_code,p.registration_no=row.registration_no,p.created_at=datetime() SET p.product_name=row.product_name MERGE (p)-[:PRODUCT_OF]->(b) FOREACH (_ IN CASE trim(row.registration_id) WHEN '' THEN [] ELSE [1] END | MERGE (reg:RegistrationIdentifier {registration_id:row.registration_id}) SET reg.raw_value=row.registration_no MERGE (p)-[:REGISTERED_AS]->(reg)) } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///consumable_product_evidence.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MATCH (p:ConsumableProduct {product_id:row.product_id}) MERGE (record)-[:EVIDENCE_FOR]->(p) } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///basic_materials.csv' AS row
CALL { WITH row MERGE (b:BasicMaterial {basic_material_id:row.basic_material_id}) SET b.name=row.name } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///consumable_skus.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MATCH (b:ConsumableBase {base_code:row.base_code}) OPTIONAL MATCH (p:ConsumableProduct {product_id:row.product_id}) MERGE (s:ConsumableSku {sku_code:row.sku_code}) ON CREATE SET s.created_at=datetime() SET s.specification=row.specification,s.model=row.model MERGE (s)-[:SKU_OF]->(b) MERGE (record)-[:EVIDENCE_FOR]->(s) FOREACH (_ IN CASE WHEN p IS NULL THEN [] ELSE [1] END | MERGE (s)-[:SKU_FOR_PRODUCT]->(p)) } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///mapping_labels.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MATCH (c:MappingConcept {namespace:row.namespace,code:row.code}) MERGE (l:ObservedLabel {observed_label_id:row.observed_label_id}) ON CREATE SET l.namespace=row.namespace,l.code=row.code,l.label=row.label MERGE (c)-[r:HAS_OBSERVED_LABEL {assertion_id:row.assertion_id}]->(l) ON CREATE SET r.source_row=toInteger(row.source_row),r.review_status='RAW' MERGE (record)-[:EVIDENCE_FOR]->(c) } IN TRANSACTIONS OF 5000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///mapping_assertions.csv' AS row
CALL { WITH row WHERE row.relation_type='ASSERTED_MAPS_TO_CONCEPT' MATCH (record:CatalogRecord {record_id:row.record_id}) MATCH (p:ConsumableProduct {product_id:row.product_id}) MATCH (c:MappingConcept {namespace:row.namespace,code:row.code}) MERGE (p)-[r:ASSERTED_MAPS_TO_CONCEPT {assertion_id:row.assertion_id}]->(c) ON CREATE SET r.batch_id=row.batch_id,r.record_id=row.record_id,r.source_file=row.source_file,r.source_sheet=row.source_sheet,r.source_row=toInteger(row.source_row),r.source_column=row.source_column,r.raw_value=row.raw_token,r.evidence_tier='RAW_ASSERTED',r.review_status='ACCEPTED',r.valid_from=CASE trim(row.valid_from) WHEN '' THEN null ELSE date(row.valid_from) END,r.valid_to=CASE trim(row.valid_to) WHEN '' THEN null ELSE date(row.valid_to) END MERGE (record)-[:EVIDENCE_FOR]->(c) } IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///mapping_assertions.csv' AS row
CALL { WITH row WHERE row.relation_type='ASSERTED_BASIC_FOR_CONCEPT' MATCH (p:ConsumableProduct {product_id:row.product_id}) MATCH (c:MappingConcept {namespace:row.namespace,code:row.code}) MATCH (m:BasicMaterial {basic_material_id:row.basic_material_id}) MERGE (p)-[r:ASSERTED_BASIC_FOR_CONCEPT {assertion_id:row.assertion_id}]->(c) ON CREATE SET r.basic_material_id=row.basic_material_id,r.raw_value=row.raw_token,r.review_status='ACCEPTED' MERGE (m)-[:EVIDENCE_FOR]->(c) } IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///concept_mentions.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MATCH (c:MappingConcept {namespace:row.namespace,code:row.code}) MERGE (record)-[r:ASSERTED_MENTIONS_CONCEPT {assertion_id:row.assertion_id}]->(c) ON CREATE SET r.raw_value=row.raw_token,r.source_row=toInteger(row.source_row),r.evidence_tier='RAW_ASSERTED' } IN TRANSACTIONS OF 1000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///drug_products.csv' AS row
CALL { WITH row MATCH (record:CatalogRecord {record_id:row.record_id}) MERGE (g:DrugGeneric {drug_generic_id:row.drug_generic_id}) ON CREATE SET g.name=row.generic_name MERGE (d:DrugProduct {drug_code:row.drug_code}) ON CREATE SET d.created_at=datetime() SET d.generic_name=row.generic_name,d.specification=row.specification,d.max_price_raw=row.max_price_raw,d.max_price=CASE trim(row.max_price) WHEN '' THEN null ELSE toFloat(row.max_price) END,d.max_price_semantics=row.max_price_semantics MERGE (d)-[:HAS_GENERIC]->(g) MERGE (record)-[:EVIDENCE_FOR]->(d) FOREACH (_ IN CASE trim(row.organization_id) WHEN '' THEN [] ELSE [1] END | MERGE (o:Organization {organization_id:row.organization_id}) SET o.normalized_name=row.organization_normalized_name MERGE (a:OrganizationAlias {alias_id:row.organization_alias_id}) SET a.raw_name=row.organization_raw_name MERGE (o)-[:HAS_ALIAS]->(a) MERGE (d)-[:MANUFACTURED_BY]->(o)) } IN TRANSACTIONS OF 5000 ROWS;
