import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const component = readFileSync(new URL('./GraphifyDataQueryChat.vue', import.meta.url), 'utf8')
const assistantMessage = readFileSync(new URL('./GraphifyAssistantMessage.vue', import.meta.url), 'utf8')
const graphView = readFileSync(new URL('./GraphifyGraphView.vue', import.meta.url), 'utf8')
const echartsGraph = readFileSync(new URL('./GraphifyEchartsGraph.vue', import.meta.url), 'utf8')
const graphExplorerModal = readFileSync(new URL('./GraphExplorerModal.vue', import.meta.url), 'utf8')
const evidenceAdapter = readFileSync(new URL('./evidenceAdapter.ts', import.meta.url), 'utf8')
const chat = readFileSync(new URL('../../views/Chat/index.vue', import.meta.url), 'utf8')
const chatMain = readFileSync(new URL('../../components/chat/ChatMain.vue', import.meta.url), 'utf8')
const messageList = readFileSync(new URL('../../components/chat/MessageList.vue', import.meta.url), 'utf8')
const chatStream = readFileSync(new URL('../../composables/chat/useChatStream.ts', import.meta.url), 'utf8')
const runActivity = readFileSync(new URL('../../components/chat/AgentRunActivity.vue', import.meta.url), 'utf8')
const questionSkill = readFileSync(new URL('../../../../skills/skills/medical-catalog-question-semantics/SKILL.md', import.meta.url), 'utf8')
const systemPrompt = readFileSync(new URL('../../../../docs/operations/medical-catalog-question-semantics-system-prompt.md', import.meta.url), 'utf8')

test('graphify route delegates empty state to the shared DIY welcome instead of local quick questions', () => {
  assert.doesNotMatch(component, /const QUICK_QUESTIONS/)
  assert.doesNotMatch(component, /class="graphify-quick-intro"/)
  assert.doesNotMatch(component, /class="graphify-quick-pills"/)
  assert.doesNotMatch(component, /sendQuickQuestion\(/)
})

test('graphify route enables published DIY config loading on the shared chat view', () => {
  assert.match(component, /:force-diy-config="true"/)
  assert.match(chat, /forceDiyConfig\?: boolean/)
  assert.match(chat, /const shouldLoadDiyConfig = computed\(\(\) => isDiyRoute\.value \|\| props\.forceDiyConfig === true\)/)
  assert.match(chat, /watch\(\s*\[shouldLoadDiyConfig, agentId\]/)
  assert.match(chat, /if \(!enabled \|\| !currentAgentId\) return/)
  assert.match(chat, /const response = await agentDiyApi\.getPublished\(currentAgentId\)/)
})

test('graphify route keeps the shared welcome layout visible for DIY cards and input', () => {
  assert.doesNotMatch(component, /:deep\(\.graphify-data-query-chat \.chat-welcome-title\)[\s\S]*?display:\s*none/)
  const chatWelcomeStyle = component.match(/:deep\(\.graphify-data-query-chat \.chat-welcome\)\s*\{[\s\S]*?\n\}/)?.[0] ?? ''
  assert.doesNotMatch(chatWelcomeStyle, /justify-content:\s*flex-end/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.chat-welcome-input\)\s*\{[\s\S]*?margin-top:\s*auto/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.chat-welcome\.is-diy-welcome \.chat-welcome-input\)\s*\{[\s\S]*?margin-top:\s*auto/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.chat-welcome-input\)\s*\{[\s\S]*?margin-bottom:/)
  assert.match(component, /\.graphify-data-query-chat-shell\s*\{[\s\S]*?display:\s*flex[\s\S]*?flex-direction:\s*column[\s\S]*?min-height:\s*100vh/)
  assert.match(component, /\.graphify-data-query-chat-shell\s*\{[\s\S]*?height:\s*100vh/)
  const chatRootStyle = component.match(/:deep\(\.graphify-data-query-chat\)\s*\{[\s\S]*?\n\}/)?.[0] ?? ''
  assert.doesNotMatch(chatRootStyle, /height:\s*100%/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.chat-welcome-container\)\s*\{[\s\S]*?min-height:\s*0[\s\S]*?height:\s*100%/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.chat-welcome\)\s*\{[\s\S]*?height:\s*100%[\s\S]*?justify-content:\s*flex-start/)
  assert.match(chatMain, /:diy-config="diyConfig"/)
})

test('graphify route keeps DIY question cards compact and readable', () => {
  assert.match(component, /:deep\(\.graphify-data-query-chat \.diy-welcome-content\)\s*\{[\s\S]*?width:\s*min\(100%,\s*1120px\)/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.diy-question-card\)\s*\{[\s\S]*?max-width:\s*360px[\s\S]*?min-height:\s*clamp\(96px,\s*11vh,\s*112px\)/)
  assert.match(component, /:deep\(\.graphify-data-query-chat \.diy-question-icon\)\s*\{[\s\S]*?width:\s*48px[\s\S]*?height:\s*48px/)
  assert.match(component, /@media\s*\(max-width:\s*767px\)\s*\{[\s\S]*?:deep\(\.graphify-data-query-chat \.diy-question-card\)\s*\{[\s\S]*?flex-basis:\s*100%/)
})

test('graphify route greets the user with a query prompt instead of the agent name', () => {
  assert.match(component, /welcome-headline-override="你想查询什么信息？"/)
  assert.match(chat, /welcomeHeadlineOverride\?: string/)
  assert.match(chat, /const displayDiyConfig = computed\(\(\) => \{/)
  assert.match(chat, /headline: headlineOverride/)
  assert.match(chat, /:diy-config="displayDiyConfig"/)
})

test('each answer owns a Neo4j graph action instead of a global recent-query action', () => {
  assert.doesNotMatch(component, /最近查询图谱/)
  assert.doesNotMatch(component, /GraphifyGraphView/)
  assert.match(component, /component: GraphifyAssistantMessage/)
  assert.match(component, /neo4jGraph: turn\?\.neo4jGraph/)
  assert.match(assistantMessage, /const resolvedNeo4jGraph = computed\(\(\) => props\.neo4jGraph \?\? \(props\.evidence \? recoverLegacyNeo4jGraph\(props\.evidence\) : null\)\)/)
  assert.match(assistantMessage, /const hasNeo4jGraph = computed\(\(\) => Boolean\(graphEvidence\.value && hasRenderableGraph\(graphEvidence\.value\)\)\)/)
  assert.match(assistantMessage, /<div v-if="hasNeo4jGraph"[\s\S]*?<button[\s\S]*?查看数据管理/)
  assert.match(assistantMessage, /<GraphifyGraphView :open="graphViewOpen" :evidence="graphEvidence"/)
})

test('answer graph action only appears for real Neo4j nodes and edges', () => {
  assert.match(assistantMessage, /neo4jGraph\?: Neo4jReadCypherGraph/)
  assert.match(assistantMessage, /v-if="hasNeo4jGraph"/)
  assert.match(assistantMessage, /const graphEvidence = computed<GraphifyEvidenceEnvelope \| undefined>/)
  assert.match(assistantMessage, /const shouldRenderResultTable = computed\(\(\) => Boolean\(contentParts\.value\.hasPlaceholder && props\.evidence && hasRows\.value\)\)/)
  assert.match(assistantMessage, /v-if="shouldRenderResultTable && evidence"/)
  assert.match(component, /if \(parseGraphifyEvidence\('', content\)\) return JSON\.stringify\(\{ name: toolName, result: content \}\)/)
})

test('knowledge graph dialog renders only the complete Neo4j graph', () => {
  assert.match(graphView, /import GraphifyEchartsGraph from '\.\/GraphifyEchartsGraph\.vue'/)
  assert.match(graphView, /const graphView = computed<GraphView \| undefined>/)
  assert.match(graphView, /buildGraphView\(props\.evidence, \{ viewMode: 'full', showFields: false \}\)/)
  assert.match(graphView, /<GraphifyEchartsGraph[\s\S]*?:graph-view="graphView"[\s\S]*?fullscreen/)
  assert.match(graphView, /@keydown\.esc="emit\('close'\)"/)
  assert.doesNotMatch(graphView, /GraphifyExecutionPath/)
  assert.doesNotMatch(graphView, /graphify-graph-view-summary/)
  assert.doesNotMatch(graphView, /graphify-graph-view-legend/)
  assert.doesNotMatch(graphView, /graphify-graph-view-actions/)
  assert.doesNotMatch(graphView, /graphify-graph-view-tools/)
  assert.match(graphView, /关闭数据管理/)
  assert.match(graphView, /@click="emit\('close'\)"/)
  assert.doesNotMatch(graphView, /查询执行链路|Wren MDL|查询字段|来源记录/)
  assert.match(echartsGraph, /type:\s*'graph'/)
  assert.match(echartsGraph, /layout:\s*'force'/)
})

test('query progress follows the latest user message and graphify alone can keep the finished card in place', () => {
  assert.match(component, /function handleRunStateChanged\(isRunning: boolean\)/)
  assert.match(component, /:on-run-state-changed="handleRunStateChanged"/)
  assert.match(component, /:run-activity-adapter="adaptQueryFlowActivities"/)
  assert.match(component, /:force-run-activity="true"/)
  assert.match(component, /run-activity-placement="after-latest-user"/)
  assert.match(component, /:retain-finished-run-activity="true"/)
  assert.match(component, /const QUERY_FLOW_STEPS/)
  assert.match(component, /function createQueryFlowActivities\(\)/)
  assert.match(component, /queryFlowActivities\.value = createQueryFlowActivities\(\)/)
  assert.match(component, /\{ id: 'answer', name: '整理回答' \}/)
  assert.match(component, /function beginAnswerComposition\(content: string\)/)
  assert.match(component, /function completeAnswerComposition\(\)/)
  assert.match(component, /const completedRunActivities = ref<RunActivity\[\]>\(\[\]\)/)
  assert.match(component, /completedRunActivities\.value = queryFlowActivities\.value\.map\(\(activity\) => \(\{ \.\.\.activity \}\)\)/)
  assert.match(component, /completedRunActivities\.value = \[\]/)
  assert.match(component, /const answerCompositionStarted = ref\(false\)/)
  assert.match(component, /answerCompositionStarted\.value && t\.status === 'running'/)
  assert.match(component, /:on-assistant-text-activity="beginAnswerComposition"/)
  assert.match(component, /evidence_subgraph:\s*'查询数据管理'/)
  assert.match(component, /parseGraphifyEvidence\('', t\.content \?\? ''\)/)
  assert.match(component, /An empty\/unsupported evidence projection is a completed optional step/)
  assert.match(component, /step\.status = 'completed'/)
  assert.match(chatStream, /const failedTool = toolCallsInProgress\.value\[toolCallsInProgress\.value\.length - 1\]/)
  assert.match(chatStream, /onToolCallActivity\?\.\(\{ toolName: failedTool\?\.name \?\? '', status: 'failed' \}\)/)
  assert.match(chatStream, /onToolCallActivity\?\.\(\{ toolName: activeTool\?\.name \?\? '', status: 'completed', content: e\.content \}\)/)
  assert.match(chat, /content\?: string/)
  assert.match(component, /const FINAL_ANSWER_ANCHOR/)
  assert.match(component, /function assistantBody\(content: string\): string/)
  assert.match(runActivity, /const expanded = ref\(true\)/)
  assert.match(runActivity, /等待\$\{activity\.label\}/)
  assert.doesNotMatch(component, /graphify-query-flow/)
  assert.match(component, /component: GraphifyAssistantMessage/)
  assert.match(chat, /onRunStateChanged\?: \(isRunning: boolean\) => void/)
  assert.match(chat, /onAssistantTextActivity\?: \(content: string\) => void/)
  assert.match(chat, /retainFinishedRunActivity\?: boolean/)
  assert.match(chat, /completedRunActivities\?: readonly RunActivity\[\]/)
  assert.match(chatStream, /onAssistantTextActivity\?\.\(currentText\)/)
  assert.match(chat, /watch\(isRunning, \(isRunning\) => \{\s*props\.onRunStateChanged\?\.\(isRunning\)/)
  assert.match(chat, /runActivityAdapter\?: \(activities: readonly RunActivity\[\]\) => RunActivity\[\]/)
  assert.match(chat, /const presentationRunActivities = computed\(\(\) =>/)
  assert.match(chat, /const presentationCompletedRunActivities = computed\(\(\) =>/)
  assert.match(chat, /:run-activities="presentationRunActivities"/)
  assert.match(chat, /:completed-run-activities="presentationCompletedRunActivities"/)
  assert.match(chat, /runActivityPlacement\?: 'tail' \| 'after-latest-user'/)
  assert.match(chat, /forceRunActivity\?: boolean/)
  assert.match(chatMain, /retainFinishedRunActivity\?: boolean/)
  assert.match(chatMain, /completedRunActivities\?: readonly RunActivity\[\]/)
  assert.match(chatMain, /:retain-finished-run-activity="retainFinishedRunActivity"/)
  assert.match(chatMain, /:completed-run-activities="completedRunActivities"/)
  assert.match(chatMain, /props\.forceRunActivity \? props\.isRunning/)
  assert.match(messageList, /retainFinishedRunActivity\?: boolean/)
  assert.match(messageList, /completedRunActivities\?: readonly RunActivity\[\]/)
  assert.match(messageList, /const retainedActivities = computed\(\(\) => props\.completedRunActivities \?\? \[\]\)/)
  assert.match(messageList, /v-else-if="retainFinishedRunActivity && retainedActivities\.length"/)
  assert.match(messageList, /:activities="retainedActivities"/)
  assert.match(messageList, /gIdx === latestUserGroupIndex/)
  assert.doesNotMatch(chatMain, /hideRunActivity/)
})

test('uses 医保 consistently across the query assistant UI, prompt, and skill', () => {
  for (const content of [component, assistantMessage, evidenceAdapter, questionSkill, systemPrompt]) {
    assert.doesNotMatch(content, /医药|医疗/)
  }
  assert.match(component, /医保问数助手/)
  assert.match(evidenceAdapter, /medical_catalog: '医保目录'/)
  assert.match(questionSkill, /# 医保目录问题语义解析与呈现/)
  assert.match(systemPrompt, /企业级医保目录问数智能体/)
})
